package sbnz.integracija;

import com.flowershop.model.Kupac;
import com.flowershop.model.KupovinaEvent;


// rule "13"
// agenda-group "group5"
//     when
//         $k: Kupac( ukupnaCena >= 5000.0 && ukupnaCena < 10000.0 )
//     then
//         modify($k) { setPopust(10.0) }
//     	System.out.println("13: Popust 10% za kupca " + $k.getUsername());

// end

// rule "14"
// agenda-group "group5"
//     when
//         $k: Kupac( ukupnaCena >= 10000.0 && ukupnaCena < 15000.0 )
//     then
//         modify($k) { setPopust(20.0) }
//     	System.out.println("14: Popust 20% za kupca " + $k.getUsername());

// end

// rule "15"
// agenda-group "group5"
//     when
//         $k: Kupac( ukupnaCena > 15000.0 )
//     then
//         modify($k) { setPopust(30.0) }
//     	System.out.println("15: Popust 30% za kupca " + $k.getUsername());

// end



rule "Vise od 5 kupovina za 1 dan od strane jednog kupca u vrednosti preko 2000"
agenda-group "group6"
    when
        $k: Kupac( popust == 0.0 )
        $t1: KupovinaEvent($cId: kupacId)
        Number(intValue >= 3) from accumulate(
            $t2: KupovinaEvent(
                this != $t1, 
                kupacId == $cId,
                this meets[1d] $t1,
                iznos >= 2000.0
            ),
            count($t2)
        )
    then
        modify($k) { setPopust(10.0) }
        System.out.println("Popust od 10% za kupca " + $k.getUsername());
end

rule "Vise od 5 kupovina za 1 dan od strane jednog kupca u vrednosti preko 3000"
agenda-group "group6"
    when
        $k: Kupac( popust != 20.0 )
        $t1: KupovinaEvent($cId: kupacId)
        Number(intValue >= 5) from accumulate(
            $t2: KupovinaEvent(
                this != $t1, 
                kupacId == $cId,
                this meets[1d] $t1,
                iznos >= 3000.0
            ),
            count($t2)
        )
    then
        modify($k) { setPopust(20.0) }
        System.out.println("Popust od 20% za kupca " + $k.getUsername());
end