package rules

import com.flowershop.model.Zahtev;
import com.flowershop.model.Cvet;
import com.flowershop.model.Cvet.Sezona;
import com.flowershop.model.VrsteCveca;
import com.flowershop.model.TipoviProizvoda;
import com.flowershop.model.TipProizvoda;

import java.util.List;


rule "8"
agenda-group "group2"
salience 10
    when
        $z: Zahtev( razlogKupovine == "pomen" || razlogKupovine == "vencanje", maxCena >= 5000.0 )
        $tp: TipoviProizvoda()
    then
        modify( $tp ) { getTipovi().add(TipProizvoda.VENAC) }
        System.out.println("8");
end

rule "9"
agenda-group "group2"
salience 10
    when
        $z: Zahtev( razlogKupovine != "pomen" )
        $tp: TipoviProizvoda()
        $vrste: VrsteCveca()
        $list: List( size > 0 ) from collect(Cvet( tipoviProizvoda contains TipProizvoda.SAKSIJSKO_CVECE ) from $vrste.getCvece())
    then
        modify( $tp ) { getTipovi().add(TipProizvoda.SAKSIJSKO_CVECE) }
        System.out.println("9");
end


rule "10"
agenda-group "group2"
salience 9
    when
        $z: Zahtev()
        $tp: TipoviProizvoda()
        $vrste: VrsteCveca()
        $list: List( size > 0 ) from collect(Cvet( tipoviProizvoda contains TipProizvoda.BUKET ) from $vrste.getCvece())
    then
        modify( $tp ) { getTipovi().add(TipProizvoda.BUKET) }
        System.out.println("10");
end

rule "10.5"
agenda-group "group2"
salience 9
    when
        $z: Zahtev()
        $tp: TipoviProizvoda()
        $vrste: VrsteCveca()
        $list: List( size > 0 ) from collect(Cvet( tipoviProizvoda contains TipProizvoda.ARANZMAN ) from $vrste.getCvece())
    then
        modify( $tp ) { getTipovi().add(TipProizvoda.ARANZMAN) }
        System.out.println("10.5");
end


// query containsBuket( VrsteCveca vrste )
//     List() from collect(Cvet( TipoviProizvoda contains TipProizvoda.BUKET ) from vrste.getCvece())
//     or
//     List() from collect(Cvet( TipoviProizvoda contains TipProizvoda.ARANZMAN ) from vrste.getCvece())
// end