package rules

import com.flowershop.model.Zahtev;
import com.flowershop.model.Cvet;
import com.flowershop.model.Cvet.Sezona;
import com.flowershop.model.VrsteCveca;
import java.util.List;


rule "1"
agenda-group "group1"
salience 10
    when
        $z: Zahtev( razlogKupovine == "vencanje" || razlogKupovine == "pomen" || razlogKupovine == "dom" || razlogKupovine == "slava", $razlog: razlogKupovine )
        $vrste: VrsteCveca()
        $preporuceneVrste: List() from collect(Cvet( simbolika contains $razlog ) from $vrste.getCvece())
    then
        modify( $vrste ) { setCvece($preporuceneVrste), setRed(1) }
        System.out.println("1");
end


rule "2"
agenda-group "group1"
salience 10
    when
        $z: Zahtev( razlogKupovine == "Dan zena", motiv == "" || motiv == null )
        $vrste: VrsteCveca()
        $preporuceneVrste: List() from collect(
            Cvet( simbolika contains "Dan zena", sezone contains Sezona.ZIMA 
            ) from $vrste.getCvece())
    then
        modify( $vrste ) { setCvece($preporuceneVrste), setRed(2) }
    	System.out.println("2");

end


rule "2.1"
agenda-group "group1"
salience 9
    when
        $z: Zahtev( razlogKupovine == "Dan zena", motiv != "" && motiv != null, $motiv: motiv )
        $vrste: VrsteCveca()
        $preporuceneVrste1: List() from collect(
            Cvet( simbolika contains "Dan zena" || simbolika contains $motiv, sezone contains Sezona.ZIMA 
            ) from $vrste.getCvece())
    then
        modify( $vrste ) { 
            setCvece($preporuceneVrste1), setRed(2)
        }
    	System.out.println("2.1");

end


rule "3"
agenda-group "group1"
salience 10
    when
        $z: Zahtev( $motiv: motiv , razlogKupovine == "ostalo")
        $vrste: VrsteCveca()
        $preporuceneVrste: List() from collect(Cvet( simbolika contains $motiv ) from $vrste.getCvece())
    then
        modify( $vrste ) { setCvece($preporuceneVrste), setRed(1) }
    	System.out.println("3");

end

rule "4"
agenda-group "group1"
salience 10
    when
        $z: Zahtev( razlogKupovine == "poseta" )
        $vrste: VrsteCveca()
        $preporuceneVrste: List() from collect(
            Cvet( simbolika contains "poseta", miris == Cvet.Miris.NEMA 
            ) from $vrste.getCvece())
    then
        modify( $vrste ) { setCvece($preporuceneVrste), setRed(1) }
    	System.out.println("4");
end


rule "5"
agenda-group "group1"
salience 8
    when
        $z: Zahtev( $sezona: sezona, razlogKupovine != "Dan zena" )
        $vrste: VrsteCveca()
        $preporuceneVrste: List() from collect(Cvet( sezone contains $sezona ) from $vrste.getCvece())
    then
        modify( $vrste ) { setCvece($preporuceneVrste), setRed(2) }
    	System.out.println("5");

end